import { connectDB } from "@/lib/db";
import Client from "@/models/Client";
import { getUser } from "@/middleware/auth";
import { getErrorMessage } from "@/lib/errors";
import { logAudit } from "@/lib/audit";
import { NextResponse } from "next/server";
import { randomBytes } from "crypto";

type RouteContext = { params: Promise<{ id: string }> };

// Super-admin only. CLIENT_ADMIN never sees or rotates the webhook key —
// the platform team owns this secret since it gates server-to-server
// integrations the client doesn't directly configure.
export async function POST(req: Request, ctx: RouteContext) {
  try {
    await connectDB();
    const user = getUser(req);

    if (user.role !== "SUPER_ADMIN") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const { id } = await ctx.params;
    const newKey = randomBytes(16).toString("hex");

    const client = await Client.findByIdAndUpdate(
      id,
      { webhookKey: newKey },
      { new: true },
    );

    if (!client) {
      return NextResponse.json({ error: "Client not found" }, { status: 404 });
    }

    await logAudit(req, { actorType: "user", user }, {
      action: "admin.client.webhookKey.rotated",
      entityType: "Client",
      entityId: client._id.toString(),
      entityLabel: client.name,
      summary: "Webhook key regenerated by super admin",
    });

    return NextResponse.json({
      message: "Webhook key regenerated",
      webhookKey: client.webhookKey,
    });
  } catch (err: unknown) {
    return NextResponse.json({ error: getErrorMessage(err) }, { status: 500 });
  }
}
