import { prisma } from "@/lib/prisma";
import { Prisma } from "@/generated/prisma/client";
import { getUser } from "@/middleware/auth";
import { getErrorMessage } from "@/lib/errors";
import { logAudit } from "@/lib/audit";
import { NextResponse } from "next/server";
import { randomBytes } from "crypto";

type RouteContext = { params: Promise<{ id: string }> };

// Super-admin only. CLIENT_ADMIN never sees or rotates the webhook key —
// the platform team owns this secret since it gates server-to-server
// integrations the client doesn't directly configure.
export async function POST(req: Request, ctx: RouteContext) {
  try {
    const user = getUser(req);

    if (user.role !== "SUPER_ADMIN") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const { id } = await ctx.params;
    const newKey = randomBytes(16).toString("hex");

    let client;
    try {
      client = await prisma.client.update({
        where: { id },
        data: { webhookKey: newKey },
        select: { id: true, name: true, webhookKey: true },
      });
    } catch (err: unknown) {
      if (
        err instanceof Prisma.PrismaClientKnownRequestError &&
        err.code === "P2025"
      ) {
        return NextResponse.json(
          { error: "Client not found" },
          { status: 404 },
        );
      }
      throw err;
    }

    await logAudit(req, { actorType: "user", user }, {
      action: "admin.client.webhookKey.rotated",
      entityType: "Client",
      entityId: client.id,
      entityLabel: client.name,
      summary: "Webhook key regenerated by super admin",
    });

    return NextResponse.json({
      message: "Webhook key regenerated",
      webhookKey: client.webhookKey,
    });
  } catch (err: unknown) {
    return NextResponse.json({ error: getErrorMessage(err) }, { status: 500 });
  }
}
