// Seed data for the VGAII CRM. IDs use a `seed_` prefix so they're easy
// to spot vs cuid-shaped production data, and so re-running the seed
// idempotently upserts the same rows.

export const password = "Password@123";

export const ids = {
  clients: {
    dental: "seed_client_dental",
    fitness: "seed_client_fitness",
  },
  users: {
    superAdmin: "seed_user_super_admin",
    dentalAdmin: "seed_user_dental_admin",
    dentalStaffLeads: "seed_user_dental_staff_leads",
    fitnessAdmin: "seed_user_fitness_admin",
    fitnessStaffReviews: "seed_user_fitness_staff_reviews",
  },
  leads: {
    dentalOne: "seed_lead_dental_one",
    dentalTwo: "seed_lead_dental_two",
    dentalThree: "seed_lead_dental_three",
    fitnessOne: "seed_lead_fitness_one",
    fitnessTwo: "seed_lead_fitness_two",
  },
  appointments: {
    dentalOne: "seed_appt_dental_one",
    dentalTwo: "seed_appt_dental_two",
    fitnessOne: "seed_appt_fitness_one",
    fitnessOrphan: "seed_appt_fitness_orphan",
  },
  feedback: {
    dentalOpen: "seed_fb_dental_open",
    fitnessResolved: "seed_fb_fitness_resolved",
  },
};

export const clients = [
  {
    id: ids.clients.dental,
    name: "Aarogya Dental Studio",
    subscriptionStatus: "active" as const,
    renewalDate: new Date("2026-12-31T00:00:00.000Z"),
    googlePlaceId: "ChIJ0UngSh9N4DsRDogoKNznAN4",
    plan: "pro",
    webhookKey: "seed_webhook_dental_key",
  },
  {
    id: ids.clients.fitness,
    name: "PulseFit Wellness",
    subscriptionStatus: "trial" as const,
    renewalDate: new Date("2026-06-30T00:00:00.000Z"),
    googlePlaceId: "ChIJseedPulseFitWellness",
    plan: "basic",
    webhookKey: "seed_webhook_fitness_key",
  },
];

export const users = [
  {
    id: ids.users.superAdmin,
    name: "Platform Admin",
    email: "superadmin@test.local",
    role: "SUPER_ADMIN" as const,
    clientId: null,
    assignedModules: [] as string[],
  },
  {
    id: ids.users.dentalAdmin,
    name: "Dental Client Admin",
    email: "dental.admin@test.local",
    role: "CLIENT_ADMIN" as const,
    clientId: ids.clients.dental,
    assignedModules: [] as string[],
  },
  {
    id: ids.users.dentalStaffLeads,
    name: "Dental Front Desk",
    email: "dental.staff@test.local",
    role: "STAFF" as const,
    clientId: ids.clients.dental,
    assignedModules: ["leads", "patients", "appointments"],
  },
  {
    id: ids.users.fitnessAdmin,
    name: "Fitness Client Admin",
    email: "fitness.admin@test.local",
    role: "CLIENT_ADMIN" as const,
    clientId: ids.clients.fitness,
    assignedModules: [] as string[],
  },
  {
    id: ids.users.fitnessStaffReviews,
    name: "Fitness Reputation Staff",
    email: "fitness.staff@test.local",
    role: "STAFF" as const,
    clientId: ids.clients.fitness,
    assignedModules: ["feedback"],
  },
];

export const leads = [
  {
    id: ids.leads.dentalOne,
    name: "Rahul Mehta",
    phone: "9876543210",
    area: "Vijay Nagar",
    source: "google-ads-form",
    status: "qualified" as const,
    statusUpdatedAt: new Date("2026-04-28T08:00:00.000Z"),
    feedbackToken: "seed-feedback-token-dental-one",
    notes: "",
    clientId: ids.clients.dental,
    createdById: ids.users.dentalStaffLeads,
  },
  {
    id: ids.leads.dentalTwo,
    name: "Sneha Kapoor",
    phone: "9876501234",
    area: "Palasia",
    source: "facebook-ads",
    status: "appointment_booked" as const,
    statusUpdatedAt: new Date("2026-04-29T10:00:00.000Z"),
    feedbackToken: "seed-feedback-token-dental-two",
    notes: "",
    clientId: ids.clients.dental,
    createdById: ids.users.dentalAdmin,
  },
  {
    id: ids.leads.dentalThree,
    name: "Amit Jain",
    phone: "9898989898",
    area: "Scheme 54",
    source: "google-ads-form",
    status: "visited" as const,
    statusUpdatedAt: new Date("2026-04-30T11:00:00.000Z"),
    outcomeRating: 2,
    feedbackToken: "seed-feedback-token-dental-three",
    feedbackTokenUsed: true,
    notes: "",
    clientId: ids.clients.dental,
    createdById: ids.users.dentalStaffLeads,
  },
  {
    id: ids.leads.fitnessOne,
    name: "Priya Sharma",
    phone: "9123456780",
    area: "Bandra",
    source: "instagram-ads",
    status: "appointment_booked" as const,
    statusUpdatedAt: new Date("2026-04-29T09:00:00.000Z"),
    feedbackToken: "seed-feedback-token-fitness-one",
    notes: "",
    clientId: ids.clients.fitness,
    createdById: ids.users.fitnessAdmin,
  },
  {
    id: ids.leads.fitnessTwo,
    name: "Karan Malhotra",
    phone: "9000011111",
    area: "Andheri",
    source: "instagram-ads",
    status: "lost" as const,
    statusUpdatedAt: new Date("2026-04-27T13:00:00.000Z"),
    feedbackToken: "seed-feedback-token-fitness-two",
    notes: "",
    clientId: ids.clients.fitness,
    createdById: ids.users.fitnessAdmin,
  },
];

export const appointments = [
  {
    id: ids.appointments.dentalOne,
    name: "Sneha Kapoor",
    phone: "9876501234",
    email: "sneha@example.com",
    gender: "female",
    age: 31,
    date: new Date("2026-05-02T10:30:00.000Z"),
    status: "scheduled" as const,
    notes: "",
    diagnosis: "",
    medicines: [] as string[],
    clientId: ids.clients.dental,
    leadId: ids.leads.dentalTwo,
    source: "cal.com",
  },
  {
    id: ids.appointments.dentalTwo,
    name: "Amit Jain",
    phone: "9898989898",
    email: "amit@example.com",
    gender: "male",
    age: 42,
    date: new Date("2026-05-04T15:00:00.000Z"),
    status: "scheduled" as const,
    notes: "",
    diagnosis: "",
    medicines: [] as string[],
    clientId: ids.clients.dental,
    leadId: ids.leads.dentalThree,
    source: "cal.com",
  },
  {
    id: ids.appointments.fitnessOne,
    name: "Priya Sharma",
    phone: "9123456780",
    email: "priya@example.com",
    gender: "female",
    age: 27,
    date: new Date("2026-05-03T07:00:00.000Z"),
    status: "scheduled" as const,
    notes: "",
    diagnosis: "",
    medicines: [] as string[],
    clientId: ids.clients.fitness,
    leadId: ids.leads.fitnessOne,
    source: "cal.com",
  },
  {
    id: ids.appointments.fitnessOrphan,
    name: "Walk-in Visitor",
    phone: "9555512345",
    email: "walkin@example.com",
    gender: "male",
    age: 35,
    date: new Date("2026-05-05T09:00:00.000Z"),
    status: "scheduled" as const,
    notes: "",
    diagnosis: "",
    medicines: [] as string[],
    clientId: ids.clients.fitness,
    leadId: null,
    source: "cal.com",
  },
];

export const feedback = [
  {
    id: ids.feedback.dentalOpen,
    clientName: "Amit Jain",
    clientPhone: "9898989898",
    reviewText: "Waited 45 minutes past my slot and got no apology.",
    rating: 2,
    leadId: ids.leads.dentalThree,
    submittedAt: new Date("2026-04-30T11:30:00.000Z"),
    status: "open" as const,
    clientId: ids.clients.dental,
  },
  {
    id: ids.feedback.fitnessResolved,
    clientName: "Karan Malhotra",
    clientPhone: "9000011111",
    reviewText: "Trainer was unavailable on the day I had booked.",
    rating: 2,
    remark: "Resolved by branch manager — comp session offered.",
    leadId: ids.leads.fitnessTwo,
    submittedAt: new Date("2026-04-27T13:30:00.000Z"),
    status: "resolved" as const,
    clientId: ids.clients.fitness,
  },
];
